version: "3"
services:
  ytfammongodb:
    image: mongo:latest
    container_name: "ytfammongodb"
    ports:
      - 27017:27017
  springboot-sortytsearch:
    image: springboot-sortytsearch:1.0
    container_name: springboot-container
    ports:
      - 8080:8080
    links:
      - ytfammongodb
    environment:
      YT_ACCESS_KEYS : "${YT_ACCESS_KEYS}"


